Updated history carousel with movie cards & implemented watched button
rpp36-boc-catamaran/getflix pull request #13
Opened 2022-10-14 18:48 UTC by shiweicc

- Updated history carousel with displaying movie cards 
- Implemented watched button function and added to main page

2022-10-14 19:08 UTC, tidibubu approved these changes

2022-10-15 15:54 UTC, AdilovM approved these changes

2022-10-15 15:57 UTC, AdilovM requested changes
please pull from upstream and repush it. there is a conflict in main.js component

2022-10-15 17:40 UTC, AdilovM approved these changes

2022-10-15 17:40 UTC, merged